apiVersion: v1
kind: Secret

metadata:
  name: mysecret
  
data:
  password: dGhpc2lzYXRlc3R0aGluZy4=
  mysql_db: R2lmdGNhcmRTaXRlREI=
  port: MzMwNg==
  user: cm9vdA==
  secret_key: a21neXNhI2Z6KzkoejEqPWMweWRyaml6ayo3c3RobTJnYTF6ND1eNjEkY3hjcThiJGw=
